# Generated by Django 3.0.5 on 2020-05-31 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdb',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
